Repository ssrando/ssrando, pull requests merged in 2024-03, with the labels that each got.

#556 Update dependencies and run black
  gamepatches.py
  logic/constants.py
  logic/dump.py
  logic/inventory.py
  logic/logic_expression.py
  poetry.lock
  pyproject.toml
  randoscript.py
Labels: :screwdriver: tweak

#557 Add github templates
  .github/ISSUE_TEMPLATE/ISSUE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :screwdriver: tweak

#550 Fix Fence Hop Softlock
  patches.yaml
Labels: :hammer_and_wrench: fix

#494 show small key count when getting key
  CHANGELOG.md
  asm/custom-functions/src/rando/mod.rs
  asm/custom_symbols.txt
  asm/patch_diffs/custom_funcs_diff.txt
  asm/patch_diffs/custom_items_diff.txt
  asm/patch_diffs/ss_necessary_diff.txt
  gamepatches.py
  gui/dialogs/tricks/ui_tricks_dialog.py
  gui/ui_randogui.py
Labels: :test_tube: needs testing, :warning: conflicts, :screwdriver: tweak

#560 Change name of builds from "dist windows-latest"
  .github/workflows/build.yaml
Labels: :screwdriver: tweak

#547 💨 Zipping Zippers 💨
  asm/patch_diffs/ss_necessary_diff.txt
  asm/patches/ss_necessary.asm
Labels: :sparkles: enhancement

#563 Fix pirate nose rupee not appearing after raising the shark head
  checks.yaml
Labels: :hammer_and_wrench: fix
